name: "Build App"

on:
  pull_request:
    paths:
      - "androidApp/src/**"
      - "shared/src/**"
      - "*.gradle*"
      - "gradle/**"
    types:
      - "opened"
      - "reopened"
      - "synchronize"
  push:
    branches:
      - "main"
      - "master"
  workflow_dispatch:  # Allow manual trigger from GitHub UI
  
      
jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    name: "build"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Setup Java"
        uses: "actions/setup-java@v4"
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: "Setup Gradle"
        uses: "gradle/gradle-build-action@v3"
        with:
          generate-job-summary: false

      - name: "Grant execute permission for gradlew"
        run: "chmod +x gradlew"

      - name: "Build APK"
        run: "./gradlew androidApp:assembleRelease --no-daemon"
        
      - name: "Upload APK artifacts"
        uses: "actions/upload-artifact@v4"
        with:
          name: "app-release"
          path: "androidApp/build/outputs/apk/release/androidApp-release.apk"

      - name: Sign app APK
        uses: NoCrypt/sign-android@main        
        id: sign_app
        with:
          releaseDir: androidApp/build/outputs/apk/release
          signingKey: ${{ secrets.SIGNING_KEYSTORE }}
          keyAlias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          
      - name: "Build AAB"
        run: "./gradlew androidApp:bundleRelease --no-daemon"

      - name: "Upload AAB artifacts"
        uses: "actions/upload-artifact@v4"
        with:
          name: "app-release-bundle"
          path: "androidApp/build/outputs/bundle/release/androidApp-release.aab"
